apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-db
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-db
  template:
    metadata:
      labels:
        app: bookstore-db
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}:{{ .Values.postgres.tag }}"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: bookstore-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
